/**********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
 * other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
 * EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
 * SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO
 * THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
 * this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2025 Renesas Electronics Corporation. All rights reserved.
 *********************************************************************************************************************/
/******************************************************************************************************************//**
 * @file          RA8P1.h
 * @Version       1.0
 * @brief         Header file including information of MCU device.
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * History : DD.MM.YYYY Version  Description
 *         : 01.01.2026 1.00     First Release
 *********************************************************************************************************************/
#ifndef RA8P1_H_
#define RA8P1_H_

// MAX CPU Operationg frequency
#define CPU_OPERATING_FREQUENCY (300000000)

// External area start address
#define OSPI_CS0_START_ADDRESS (0x80000000)
#define OSPI_CS1_START_ADDRESS (0x90000000)

// Non-Secure offset
#ifdef SECURE
#define NSEC_OFFSET (0)
#else
#define NSEC_OFFSET (0x10000000)
#endif

// Module stop registers
#define MSTP_BASE    (0x40203000 + NSEC_OFFSET)
#define MSTP_MSTPCRB (MSTP_BASE + 0x4)

// I/O port registers
#define PFS_BASE          (0x40400800 + NSEC_OFFSET)
#define PmnPFS(port, pin) ((PFS_BASE) + 0x0 + (0x40 * (port)) + (0x4 * (pin)))  // Set PmnPFS
#define PFS_OM_SCLK       (PmnPFS(8, 8))  // P808
#define PFS_OM_SCLKN      (PmnPFS(8, 9))  // P809
#define PFS_OM_CS0        (PmnPFS(1, 7))  // P107
#define PFS_OM_CS1        (PmnPFS(1, 4))  // P104
#define PFS_OM_DQS        (PmnPFS(8, 1))  // P801
#define PFS_OM_SIO0       (PmnPFS(1, 0))  // P100
#define PFS_OM_SIO1       (PmnPFS(8, 3))  // P803
#define PFS_OM_SIO2       (PmnPFS(1, 3))  // P103
#define PFS_OM_SIO3       (PmnPFS(1, 1))  // P101
#define PFS_OM_SIO4       (PmnPFS(1, 2))  // P102
#define PFS_OM_SIO5       (PmnPFS(8, 0))  // P800
#define PFS_OM_SIO6       (PmnPFS(8, 2))  // P802
#define PFS_OM_SIO7       (PmnPFS(8, 4))  // P804
#define PFS_OM_RESET      (PmnPFS(1, 6))  // P106
#define PFS_OM_ECSINT1    (PmnPFS(1, 5))  // P105
#define PFS_OM_RSTO1      (PmnPFS(6, 0))  // P600
#define PFS_OM_WP1        (PmnPFS(6, 1))  // P601
#ifdef SECURE
#define PFS_PWPR          (PFS_BASE + 0x514)
#else
#define PFS_PWPR          (PFS_BASE + 0x50C)
#endif

// OSPI unit0 registers
#define OSPI_BASE      (0x40268000 + NSEC_OFFSET)
#define OSPI_WRAPCFG   (OSPI_BASE + 0x0)
#define OSPI_COMCFG    (OSPI_BASE + 0x4)
#define OSPI_BMCFGCH0  (OSPI_BASE + 0x8 + 0x4 * 0)
#define OSPI_BMCFGCH1  (OSPI_BASE + 0x8 + 0x4 * 1)
#define OSPI_CMCFG0CS0 (OSPI_BASE + 0x10 + 0x10 * 0)
#define OSPI_CMCFG0CS1 (OSPI_BASE + 0x10 + 0x10 * 1)
#define OSPI_CMCFG1CS0 (OSPI_BASE + 0x14 + 0x10 * 0)
#define OSPI_CMCFG1CS1 (OSPI_BASE + 0x14 + 0x10 * 1)
#define OSPI_CMCFG2CS0 (OSPI_BASE + 0x18 + 0x10 * 0)
#define OSPI_CMCFG2CS1 (OSPI_BASE + 0x18 + 0x10 * 1)
#define OSPI_LIOCFGCS0 (OSPI_BASE + 0x50 + 0x4 * 0)
#define OSPI_LIOCFGCS1 (OSPI_BASE + 0x50 + 0x4 * 1)
#define OSPI_BMCTL0    (OSPI_BASE + 0x60)
#define OSPI_BMCTL1    (OSPI_BASE + 0x64)
#define OSPI_CMCTLCH0  (OSPI_BASE + 0x68 + 0x4 * 0)
#define OSPI_CMCTLCH1  (OSPI_BASE + 0x68 + 0x4 * 1)
#define OSPI_CDCTL0    (OSPI_BASE + 0x70)
#define OSPI_CDCTL1    (OSPI_BASE + 0x74)
#define OSPI_CDCTL2    (OSPI_BASE + 0x78)
#define OSPI_CDTBUF0   (OSPI_BASE + 0x80 + 0x10 * 0)
#define OSPI_CDTBUF1   (OSPI_BASE + 0x80 + 0x10 * 1)
#define OSPI_CDTBUF2   (OSPI_BASE + 0x80 + 0x10 * 2)
#define OSPI_CDTBUF3   (OSPI_BASE + 0x80 + 0x10 * 3)
#define OSPI_CDABUF0   (OSPI_BASE + 0x84 + 0x10 * 0)
#define OSPI_CDABUF1   (OSPI_BASE + 0x84 + 0x10 * 1)
#define OSPI_CDABUF2   (OSPI_BASE + 0x84 + 0x10 * 2)
#define OSPI_CDABUF3   (OSPI_BASE + 0x84 + 0x10 * 3)
#define OSPI_CDD0BUF0  (OSPI_BASE + 0x88 + 0x10 * 0)
#define OSPI_CDD0BUF1  (OSPI_BASE + 0x88 + 0x10 * 1)
#define OSPI_CDD0BUF2  (OSPI_BASE + 0x88 + 0x10 * 2)
#define OSPI_CDD0BUF3  (OSPI_BASE + 0x88 + 0x10 * 3)
#define OSPI_CDD1BUF0  (OSPI_BASE + 0x8C + 0x10 * 0)
#define OSPI_CDD1BUF1  (OSPI_BASE + 0x8C + 0x10 * 1)
#define OSPI_CDD1BUF2  (OSPI_BASE + 0x8C + 0x10 * 2)
#define OSPI_CDD1BUF3  (OSPI_BASE + 0x8C + 0x10 * 3)
#define OSPI_LPCTL0    (OSPI_BASE + 0x100)
#define OSPI_LPCTL1    (OSPI_BASE + 0x104)
#define OSPI_LIOCTL    (OSPI_BASE + 0x108)
#define OSPI_CCCTL0CS0 (OSPI_BASE + 0x130 + 0x20 * 0)
#define OSPI_CCCTL0CS1 (OSPI_BASE + 0x130 + 0x20 * 1)
#define OSPI_CCCTL1CS0 (OSPI_BASE + 0x134 + 0x20 * 0)
#define OSPI_CCCTL1CS1 (OSPI_BASE + 0x134 + 0x20 * 1)
#define OSPI_CCCTL2CS0 (OSPI_BASE + 0x138 + 0x20 * 0)
#define OSPI_CCCTL2CS1 (OSPI_BASE + 0x138 + 0x20 * 1)
#define OSPI_CCCTL3CS0 (OSPI_BASE + 0x13C + 0x20 * 0)
#define OSPI_CCCTL3CS1 (OSPI_BASE + 0x13C + 0x20 * 1)
#define OSPI_CCCTL4CS0 (OSPI_BASE + 0x140 + 0x20 * 0)
#define OSPI_CCCTL4CS1 (OSPI_BASE + 0x140 + 0x20 * 1)
#define OSPI_CCCTL5CS0 (OSPI_BASE + 0x144 + 0x20 * 0)
#define OSPI_CCCTL5CS1 (OSPI_BASE + 0x144 + 0x20 * 1)
#define OSPI_CCCTL6CS0 (OSPI_BASE + 0x148 + 0x20 * 0)
#define OSPI_CCCTL6CS1 (OSPI_BASE + 0x148 + 0x20 * 1)
#define OSPI_CCCTL7CS0 (OSPI_BASE + 0x14C + 0x20 * 0)
#define OSPI_CCCTL7CS1 (OSPI_BASE + 0x14C + 0x20 * 1)
#define OSPI_COMSTT    (OSPI_BASE + 0x184)
#define OSPI_CASTTCS0  (OSPI_BASE + 0x188 + 0x4 * 0)
#define OSPI_CASTTCS1  (OSPI_BASE + 0x188 + 0x4 * 1)
#define OSPI_INTS      (OSPI_BASE + 0x190)
#define OSPI_INTC      (OSPI_BASE + 0x194)
#define OSPI_INTE      (OSPI_BASE + 0x198)

// Register setting
#define PODR_LOW  (0UL)
#define PODR_HIGH (1UL)
#define PIDR_LOW  (0UL)
#define PIDR_HIGH (1UL)
#define PDR_IN    (0UL)
#define PDR_OUT   (1UL)
#define PSEL_OSPI (0x1CUL)

#define PmnPFS_PODR_Pos (0UL)
#define PmnPFS_PIDR_Pos (1UL)
#define PmnPFS_PDR_Pos  (2UL)
#define PmnPFS_PMR_Pos  (16UL)
#define PmnPFS_PMR_Msk  (0x00010000UL)
#define PmnPFS_PSEL_Pos (24UL)
#define PmnPFS_PSEL_Msk (0x1C000000UL)
#define PWPR_PFSWE_Pos  (6UL)
#define PWPR_B0WI_Pos   (7UL)

#define MSTP_MSTPCRB_OSPI_POS (16UL)

#define OSPI_WRAPCFG_CKSFTCS0_Pos          (0UL)
#define OSPI_WRAPCFG_CKSFTCS0_Msk          (0x1fUL)
#define OSPI_WRAPCFG_DSSFTCS0_Pos          (8UL)
#define OSPI_WRAPCFG_DSSFTCS0_Msk          (0x1f00UL)
#define OSPI_WRAPCFG_CKSFTCS1_Pos          (16UL)
#define OSPI_WRAPCFG_CKSFTCS1_Msk          (0x1f0000UL)
#define OSPI_WRAPCFG_DSSFTCS1_Pos          (24UL)
#define OSPI_WRAPCFG_DSSFTCS1_Msk          (0x1f000000UL)
#define OSPI_COMCFG_ARBMD_Pos              (0UL)
#define OSPI_COMCFG_ARBMD_Msk              (0x3UL)
#define OSPI_COMCFG_ECSINTOUTEN_Pos        (4UL)
#define OSPI_COMCFG_ECSINTOUTEN_Msk        (0x30UL)
#define OSPI_COMCFG_OEASTEX_Pos            (16UL)
#define OSPI_COMCFG_OEASTEX_Msk            (0x10000UL)
#define OSPI_COMCFG_OENEGEX_Pos            (17UL)
#define OSPI_COMCFG_OENEGEX_Msk            (0x20000UL)
#define OSPI_BMCFGCH_WRMD_Pos              (0UL)
#define OSPI_BMCFGCH_WRMD_Msk              (0x1UL)
#define OSPI_BMCFGCH_MWRCOMB_Pos           (7UL)
#define OSPI_BMCFGCH_MWRCOMB_Msk           (0x80UL)
#define OSPI_BMCFGCH_MWRSIZE_Pos           (8UL)
#define OSPI_BMCFGCH_MWRSIZE_Msk           (0xff00UL)
#define OSPI_BMCFGCH_PREEN_Pos             (16UL)
#define OSPI_BMCFGCH_PREEN_Msk             (0x10000UL)
#define OSPI_BMCFGCH_CMBTIM_Pos            (24UL)
#define OSPI_BMCFGCH_CMBTIM_Msk            (0xff000000UL)
#define OSPI_LIOCFGCS_PRTMD_Pos            (0UL)
#define OSPI_LIOCFGCS_PRTMD_Msk            (0x3ffUL)
#define OSPI_LIOCFGCS_LATEMD_Pos           (10UL)
#define OSPI_LIOCFGCS_LATEMD_Msk           (0x400UL)
#define OSPI_LIOCFGCS_WRMSKMD_Pos          (11UL)
#define OSPI_LIOCFGCS_WRMSKMD_Msk          (0x800UL)
#define OSPI_LIOCFGCS_CSMIN_Pos            (16UL)
#define OSPI_LIOCFGCS_CSMIN_Msk            (0xf0000UL)
#define OSPI_LIOCFGCS_CSASTEX_Pos          (20UL)
#define OSPI_LIOCFGCS_CSASTEX_Msk          (0x100000UL)
#define OSPI_LIOCFGCS_CSNEGEX_Pos          (21UL)
#define OSPI_LIOCFGCS_CSNEGEX_Msk          (0x200000UL)
#define OSPI_LIOCFGCS_SDRDRV_Pos           (22UL)
#define OSPI_LIOCFGCS_SDRDRV_Msk           (0x400000UL)
#define OSPI_LIOCFGCS_SDRSMPMD_Pos         (23UL)
#define OSPI_LIOCFGCS_SDRSMPMD_Msk         (0x800000UL)
#define OSPI_LIOCFGCS_SDRSMPSFT_Pos        (24UL)
#define OSPI_LIOCFGCS_SDRSMPSFT_Msk        (0xf000000UL)
#define OSPI_LIOCFGCS_DDRSMPEX_Pos         (28UL)
#define OSPI_LIOCFGCS_DDRSMPEX_Msk         (0xf0000000UL)
#define OSPI_ABMCFG_ODRMD_Pos              (0UL)
#define OSPI_ABMCFG_ODRMD_Msk              (0x3UL)
#define OSPI_ABMCFG_CHSEL_Pos              (16UL)
#define OSPI_ABMCFG_CHSEL_Msk              (0xffff0000UL)
#define OSPI_BMCTL0_CH0CS0ACC_Pos          (0UL)
#define OSPI_BMCTL0_CH0CS0ACC_Msk          (0x3UL)
#define OSPI_BMCTL0_CH0CS1ACC_Pos          (2UL)
#define OSPI_BMCTL0_CH0CS1ACC_Msk          (0xcUL)
#define OSPI_BMCTL0_CH1CS0ACC_Pos          (4UL)
#define OSPI_BMCTL0_CH1CS0ACC_Msk          (0x30UL)
#define OSPI_BMCTL0_CH1CS1ACC_Pos          (6UL)
#define OSPI_BMCTL0_CH1CS1ACC_Msk          (0xc0UL)
#define OSPI_BMCTL1_MWRPUSHCH_Pos          (8UL)
#define OSPI_BMCTL1_MWRPUSHCH_Msk          (0x100UL)
#define OSPI_BMCTL1_PBUFCLRCH_Pos          (10UL)
#define OSPI_BMCTL1_PBUFCLRCH_Msk          (0x400UL)
#define OSPI_CMCTLCH_XIPENCODE_Pos         (0UL)
#define OSPI_CMCTLCH_XIPENCODE_Msk         (0xffUL)
#define OSPI_CMCTLCH_XIPEXCODE_Pos         (8UL)
#define OSPI_CMCTLCH_XIPEXCODE_Msk         (0xff00UL)
#define OSPI_CMCTLCH_XIPEN_Pos             (16UL)
#define OSPI_CMCTLCH_XIPEN_Msk             (0x10000UL)
#define OSPI_CDCTL0_TRREQ_Pos              (0UL)
#define OSPI_CDCTL0_TRREQ_Msk              (0x1UL)
#define OSPI_CDCTL0_PERMD_Pos              (1UL)
#define OSPI_CDCTL0_PERMD_Msk              (0x2UL)
#define OSPI_CDCTL0_CSSEL_Pos              (3UL)
#define OSPI_CDCTL0_CSSEL_Msk              (0x8UL)
#define OSPI_CDCTL0_TRNUM_Pos              (4UL)
#define OSPI_CDCTL0_TRNUM_Msk              (0x30UL)
#define OSPI_CDCTL0_PERITV_Pos             (16UL)
#define OSPI_CDCTL0_PERITV_Msk             (0x1f0000UL)
#define OSPI_CDCTL0_PERREP_Pos             (24UL)
#define OSPI_CDCTL0_PERREP_Msk             (0xf000000UL)
#define OSPI_CDCTL1_PEREXP_Pos             (0UL)
#define OSPI_CDCTL1_PEREXP_Msk             (0xffffffffUL)
#define OSPI_CDCTL2_PERMSK_Pos             (0UL)
#define OSPI_CDCTL2_PERMSK_Msk             (0xffffffffUL)
#define OSPI_CMCFGCS_CMCFG0_FFMT_Pos       (0UL)
#define OSPI_CMCFGCS_CMCFG0_FFMT_Msk       (0x3UL)
#define OSPI_CMCFGCS_CMCFG0_ADDSIZE_Pos    (2UL)
#define OSPI_CMCFGCS_CMCFG0_ADDSIZE_Msk    (0xcUL)
#define OSPI_CMCFGCS_CMCFG0_WPBSTMD_Pos    (4UL)
#define OSPI_CMCFGCS_CMCFG0_WPBSTMD_Msk    (0x10UL)
#define OSPI_CMCFGCS_CMCFG0_ARYAMD_Pos     (5UL)
#define OSPI_CMCFGCS_CMCFG0_ARYAMD_Msk     (0x20UL)
#define OSPI_CMCFGCS_CMCFG0_ADDRPEN_Pos    (16UL)
#define OSPI_CMCFGCS_CMCFG0_ADDRPEN_Msk    (0xff0000UL)
#define OSPI_CMCFGCS_CMCFG0_ADDRPCD_Pos    (24UL)
#define OSPI_CMCFGCS_CMCFG0_ADDRPCD_Msk    (0xff000000UL)
#define OSPI_CMCFGCS_CMCFG1_RDCMD_Pos      (0UL)
#define OSPI_CMCFGCS_CMCFG1_RDCMD_Msk      (0xffffUL)
#define OSPI_CMCFGCS_CMCFG1_RDLATE_Pos     (16UL)
#define OSPI_CMCFGCS_CMCFG1_RDLATE_Msk     (0x1f0000UL)
#define OSPI_CMCFGCS_CMCFG2_WRCMD_Pos      (0UL)
#define OSPI_CMCFGCS_CMCFG2_WRCMD_Msk      (0xffffUL)
#define OSPI_CMCFGCS_CMCFG2_WRLATE_Pos     (16UL)
#define OSPI_CMCFGCS_CMCFG2_WRLATE_Msk     (0x1f0000UL)
#define OSPI_CDBUF_CDT_CMDSIZE_Pos         (0UL)
#define OSPI_CDBUF_CDT_CMDSIZE_Msk         (0x3UL)
#define OSPI_CDBUF_CDT_ADDSIZE_Pos         (2UL)
#define OSPI_CDBUF_CDT_ADDSIZE_Msk         (0x1cUL)
#define OSPI_CDBUF_CDT_DATASIZE_Pos        (5UL)
#define OSPI_CDBUF_CDT_DATASIZE_Msk        (0x1e0UL)
#define OSPI_CDBUF_CDT_LATE_Pos            (9UL)
#define OSPI_CDBUF_CDT_LATE_Msk            (0x3e00UL)
#define OSPI_CDBUF_CDT_TRTYPE_Pos          (15UL)
#define OSPI_CDBUF_CDT_TRTYPE_Msk          (0x8000UL)
#define OSPI_CDBUF_CDT_CMD_Pos             (16UL)
#define OSPI_CDBUF_CDT_CMD_Msk             (0xffff0000UL)
#define OSPI_CDBUF_CDT_CMD_1B_Pos          (24UL)
#define OSPI_CDBUF_CDT_CMD_1B_Msk          (0xFF000000UL)
#define OSPI_CDBUF_CDT_CMD_2B_Pos          (16UL)
#define OSPI_CDBUF_CDT_CMD_2B_Msk          (0xFFFF0000UL)
#define OSPI_CDBUF_CDA_ADD_Pos             (0UL)
#define OSPI_CDBUF_CDA_ADD_Msk             (0xffffffffUL)
#define OSPI_CDBUF_CDD0_DATA_Pos           (0UL)
#define OSPI_CDBUF_CDD0_DATA_Msk           (0xffffffffUL)
#define OSPI_CDBUF_CDD1_DATA_Pos           (0UL)
#define OSPI_CDBUF_CDD1_DATA_Msk           (0xffffffffUL)
#define OSPI_CCCTLCS_CCCTL0_CAEN_Pos       (0UL)
#define OSPI_CCCTLCS_CCCTL0_CAEN_Msk       (0x1UL)
#define OSPI_CCCTLCS_CCCTL0_CANOWR_Pos     (1UL)
#define OSPI_CCCTLCS_CCCTL0_CANOWR_Msk     (0x2UL)
#define OSPI_CCCTLCS_CCCTL0_CAITV_Pos      (8UL)
#define OSPI_CCCTLCS_CCCTL0_CAITV_Msk      (0x1f00UL)
#define OSPI_CCCTLCS_CCCTL0_CASFTSTA_Pos   (16UL)
#define OSPI_CCCTLCS_CCCTL0_CASFTSTA_Msk   (0x1f0000UL)
#define OSPI_CCCTLCS_CCCTL0_CASFTEND_Pos   (24UL)
#define OSPI_CCCTLCS_CCCTL0_CASFTEND_Msk   (0x1f000000UL)
#define OSPI_CCCTLCS_CCCTL1_CACMDSIZE_Pos  (0UL)
#define OSPI_CCCTLCS_CCCTL1_CACMDSIZE_Msk  (0x3UL)
#define OSPI_CCCTLCS_CCCTL1_CAADDSIZE_Pos  (2UL)
#define OSPI_CCCTLCS_CCCTL1_CAADDSIZE_Msk  (0x1cUL)
#define OSPI_CCCTLCS_CCCTL1_CADATASIZE_Pos (5UL)
#define OSPI_CCCTLCS_CCCTL1_CADATASIZE_Msk (0x1e0UL)
#define OSPI_CCCTLCS_CCCTL1_CAWRLATE_Pos   (16UL)
#define OSPI_CCCTLCS_CCCTL1_CAWRLATE_Msk   (0x1f0000UL)
#define OSPI_CCCTLCS_CCCTL1_CARDLATE_Pos   (24UL)
#define OSPI_CCCTLCS_CCCTL1_CARDLATE_Msk   (0x1f000000UL)
#define OSPI_CCCTLCS_CCCTL2_CAWRCMD_Pos    (0UL)
#define OSPI_CCCTLCS_CCCTL2_CAWRCMD_Msk    (0xffffUL)
#define OSPI_CCCTLCS_CCCTL2_CARDCMD_Pos    (16UL)
#define OSPI_CCCTLCS_CCCTL2_CARDCMD_Msk    (0xffff0000UL)
#define OSPI_CCCTLCS_CCCTL3_CAADD_Pos      (0UL)
#define OSPI_CCCTLCS_CCCTL3_CAADD_Msk      (0xffffffffUL)
#define OSPI_CCCTLCS_CCCTL4_CADATA_Pos     (0UL)
#define OSPI_CCCTLCS_CCCTL4_CADATA_Msk     (0xffffffffUL)
#define OSPI_CCCTLCS_CCCTL5_CADATA_Pos     (0UL)
#define OSPI_CCCTLCS_CCCTL5_CADATA_Msk     (0xffffffffUL)
#define OSPI_CCCTLCS_CCCTL6_CADATA_Pos     (0UL)
#define OSPI_CCCTLCS_CCCTL6_CADATA_Msk     (0xffffffffUL)
#define OSPI_CCCTLCS_CCCTL7_CADATA_Pos     (0UL)
#define OSPI_CCCTLCS_CCCTL7_CADATA_Msk     (0xffffffffUL)
#define OSPI_LPCTL0_PATREQ_Pos             (0UL)
#define OSPI_LPCTL0_PATREQ_Msk             (0x1UL)
#define OSPI_LPCTL0_CSSEL_Pos              (3UL)
#define OSPI_LPCTL0_CSSEL_Msk              (0x8UL)
#define OSPI_LPCTL0_XDPIN_Pos              (4UL)
#define OSPI_LPCTL0_XDPIN_Msk              (0x30UL)
#define OSPI_LPCTL0_XD1LEN_Pos             (16UL)
#define OSPI_LPCTL0_XD1LEN_Msk             (0x1f0000UL)
#define OSPI_LPCTL0_XD1VAL_Pos             (23UL)
#define OSPI_LPCTL0_XD1VAL_Msk             (0x800000UL)
#define OSPI_LPCTL0_XD2LEN_Pos             (24UL)
#define OSPI_LPCTL0_XD2LEN_Msk             (0x1f000000UL)
#define OSPI_LPCTL0_XD2VAL_Pos             (31UL)
#define OSPI_LPCTL0_XD2VAL_Msk             (0x80000000UL)
#define OSPI_LPCTL1_PATREQ_Pos             (0UL)
#define OSPI_LPCTL1_PATREQ_Msk             (0x3UL)
#define OSPI_LPCTL1_CSSEL_Pos              (3UL)
#define OSPI_LPCTL1_CSSEL_Msk              (0x8UL)
#define OSPI_LPCTL1_RSTREP_Pos             (4UL)
#define OSPI_LPCTL1_RSTREP_Msk             (0x30UL)
#define OSPI_LPCTL1_RSTWID_Pos             (8UL)
#define OSPI_LPCTL1_RSTWID_Msk             (0x700UL)
#define OSPI_LPCTL1_RSTSU_Pos              (12UL)
#define OSPI_LPCTL1_RSTSU_Msk              (0x7000UL)
#define OSPI_LIOCTL_WPCS_Msk               (0x1UL)
#define OSPI_LIOCTL_RSTCS_Pos              (16UL)
#define OSPI_LIOCTL_RSTCS_Msk              (0x10000UL)
#define OSPI_VERSTT_VER_Pos                (0UL)
#define OSPI_VERSTT_VER_Msk                (0xffffffffUL)
#define OSPI_COMSTT_MEMACCCH_Pos           (0UL)
#define OSPI_COMSTT_MEMACCCH_Msk           (0x1UL)
#define OSPI_COMSTT_PBUFNECH_Pos           (4UL)
#define OSPI_COMSTT_PBUFNECH_Msk           (0x10UL)
#define OSPI_COMSTT_WRBUFNECH_Pos          (6UL)
#define OSPI_COMSTT_WRBUFNECH_Msk          (0x40UL)
#define OSPI_COMSTT_ECSCS_Pos              (16UL)
#define OSPI_COMSTT_ECSCS_Msk              (0x10000UL)
#define OSPI_COMSTT_INTCS_Pos              (17UL)
#define OSPI_COMSTT_INTCS_Msk              (0x20000UL)
#define OSPI_COMSTT_RSTOCS_Pos             (18UL)
#define OSPI_COMSTT_RSTOCS_Msk             (0x40000UL)
#define OSPI_CASTTCS_CASUC_Pos             (0UL)
#define OSPI_CASTTCS_CASUC_Msk             (0xffffffffUL)
#define OSPI_INTS_CMDCMP_Pos               (0UL)
#define OSPI_INTS_CMDCMP_Msk               (0x1UL)
#define OSPI_INTS_PATCMP_Pos               (1UL)
#define OSPI_INTS_PATCMP_Msk               (0x2UL)
#define OSPI_INTS_INICMP_Pos               (2UL)
#define OSPI_INTS_INICMP_Msk               (0x4UL)
#define OSPI_INTS_PERTO_Pos                (3UL)
#define OSPI_INTS_PERTO_Msk                (0x8UL)
#define OSPI_INTS_DSTOCS_Pos               (4UL)
#define OSPI_INTS_DSTOCS_Msk               (0x10UL)
#define OSPI_INTS_ECSCS_Pos                (8UL)
#define OSPI_INTS_ECSCS_Msk                (0x100UL)
#define OSPI_INTS_INTCS_Pos                (12UL)
#define OSPI_INTS_INTCS_Msk                (0x1000UL)
#define OSPI_INTS_BRGOFCH_Pos              (16UL)
#define OSPI_INTS_BRGOFCH_Msk              (0x10000UL)
#define OSPI_INTS_BRGUFCH_Pos              (18UL)
#define OSPI_INTS_BRGUFCH_Msk              (0x40000UL)
#define OSPI_INTS_BUSERRCH_Pos             (20UL)
#define OSPI_INTS_BUSERRCH_Msk             (0x100000UL)
#define OSPI_INTS_CAFAILCS_Pos             (28UL)
#define OSPI_INTS_CAFAILCS_Msk             (0x10000000UL)
#define OSPI_INTS_CASUCCS_Pos              (30UL)
#define OSPI_INTS_CASUCCS_Msk              (0x40000000UL)
#define OSPI_INTC_CMDCMPC_Pos              (0UL)
#define OSPI_INTC_CMDCMPC_Msk              (0x1UL)
#define OSPI_INTC_PATCMPC_Pos              (1UL)
#define OSPI_INTC_PATCMPC_Msk              (0x2UL)
#define OSPI_INTC_INICMPC_Pos              (2UL)
#define OSPI_INTC_INICMPC_Msk              (0x4UL)
#define OSPI_INTC_PERTOC_Pos               (3UL)
#define OSPI_INTC_PERTOC_Msk               (0x8UL)
#define OSPI_INTC_DSTOCSC_Pos              (4UL)
#define OSPI_INTC_DSTOCSC_Msk              (0x10UL)
#define OSPI_INTC_ECSCSC_Pos               (8UL)
#define OSPI_INTC_ECSCSC_Msk               (0x100UL)
#define OSPI_INTC_INTCSC_Pos               (12UL)
#define OSPI_INTC_INTCSC_Msk               (0x1000UL)
#define OSPI_INTC_BRGOFCHC_Pos             (16UL)
#define OSPI_INTC_BRGOFCHC_Msk             (0x10000UL)
#define OSPI_INTC_BRGUFCHC_Pos             (18UL)
#define OSPI_INTC_BRGUFCHC_Msk             (0x40000UL)
#define OSPI_INTC_BUSERRCHC_Pos            (20UL)
#define OSPI_INTC_BUSERRCHC_Msk            (0x100000UL)
#define OSPI_INTC_CAFAILCSC_Pos            (28UL)
#define OSPI_INTC_CAFAILCSC_Msk            (0x10000000UL)
#define OSPI_INTC_CASUCCSC_Pos             (30UL)
#define OSPI_INTC_CASUCCSC_Msk             (0x40000000UL)
#define OSPI_INTE_CMDCMPE_Pos              (0UL)
#define OSPI_INTE_CMDCMPE_Msk              (0x1UL)
#define OSPI_INTE_PATCMPE_Pos              (1UL)
#define OSPI_INTE_PATCMPE_Msk              (0x2UL)
#define OSPI_INTE_INICMPE_Pos              (2UL)
#define OSPI_INTE_INICMPE_Msk              (0x4UL)
#define OSPI_INTE_PERTOE_Pos               (3UL)
#define OSPI_INTE_PERTOE_Msk               (0x8UL)
#define OSPI_INTE_DSTOCSE_Pos              (4UL)
#define OSPI_INTE_DSTOCSE_Msk              (0x10UL)
#define OSPI_INTE_ECSCSE_Pos               (8UL)
#define OSPI_INTE_ECSCSE_Msk               (0x100UL)
#define OSPI_INTE_INTCSE_Pos               (12UL)
#define OSPI_INTE_INTCSE_Msk               (0x1000UL)
#define OSPI_INTE_BRGOFCHE_Pos             (16UL)
#define OSPI_INTE_BRGOFCHE_Msk             (0x10000UL)
#define OSPI_INTE_BRGUFCHE_Pos             (18UL)
#define OSPI_INTE_BRGUFCHE_Msk             (0x40000UL)
#define OSPI_INTE_BUSERRCHE_Pos            (20UL)
#define OSPI_INTE_BUSERRCHE_Msk            (0x100000UL)
#define OSPI_INTE_CAFAILCSE_Pos            (28UL)
#define OSPI_INTE_CAFAILCSE_Msk            (0x10000000UL)
#define OSPI_INTE_CASUCCSE_Pos             (30UL)
#define OSPI_INTE_CASUCCSE_Msk             (0x40000000UL)

#define OSPI_LIOCFGCS_PRTMD_1S_1S_1S (0x000)
#define OSPI_LIOCFGCS_PRTMD_4S_4D_4D (0x3B2)
#define OSPI_LIOCFGCS_PRTMD_8D_8D_8D (0x3FF)
#define OSPI_LIOCFGCS_PRTMD_1S_2S_2S (0x048)
#define OSPI_LIOCFGCS_PRTMD_2S_2S_2S (0x049)
#define OSPI_LIOCFGCS_PRTMD_1S_4S_4S (0x090)
#define OSPI_LIOCFGCS_PRTMD_4S_4S_4S (0x092)

#endif  /* RA8P1_H_ */
